name = "hstack"
main= "src/index.tsx"
compatibility_date = "2023-01-01"

[site]
bucket = "./assets"

[[d1_databases]] # replace this with your own
binding = "DB"
database_name = "hstack-db"
database_id = "6a765098-d238-45c4-a7fd-9d796be20b52"

migrations_dir = "migrations"

